//constants are returned as action types which will be used in action and reducer files


export const ADD_USER_TO_STORE = "STORE.ADDUSER";
export const ADD_HOBBY_TO_STORE = "STORE.ADDHOBBY";

export const ADD_PRODUCTS_TO_STORE = "STORE.ADDPRODUCTS";
export const ADD_PRODUCT_TO_DB_AND_STORE = "STORE.ADDPRODUCTTODBANDSTORE";

export const ADD_PRODUCT_TO_CART = "STORE.ADDPRODUCTTOCART"
export const SET_USER_IN_CART = "STORE.SETUSERINCART"
export const UPDATE_CART = "STORE.UPDATE_CART"

export const ADD_COUPON = "STORE.ADDCOUPON"

export const ADD_NOTIFICATION = "STORE.ADDNOTIFICATION"
export const REMOVE_NOTIFICATION = "STORE.REMOVENOTIFICATION"